export const employeeData = [
  {
    id: 1,
    name: "Dr. Renee Oglesby, Ph.D",
    role: "CEO / Counselor Educator",
    specialty: "NCC, LCMHCS, LCAS, CRC, CSS",
    description: "CEO / Counselor Educator, Trauma, Addictions, TF-CBT, DWI ",
    imageUrl: "/images/employees/renee_oglesby.jpeg",
    linkedinUrl: "https://www.linkedin.com/in/dr-renee-oglesby-565a6b63/",
  },
  {
    id: 2,
    name: "Leah Bradshaw",
    role: "Counselor",
    specialty: "MSW, LCSWA, CBT",
    description: "Children and Adolescents, Play Therapy",
    imageUrl: "/images/employees/leah_bradshaw.jpeg",
  },
  {
    id: 3,
    name: "Michael Johnson (MJ)",
    role: "Counselor",
    specialty: "LCMHCA, CBT, REBT, SFBT",
    description: "Existentialist, Teen and Adolescent, Depression and Anxitey",
    imageUrl: "/images/employees/michael_johnson.jpeg",
  },
  {
    id: 4,
    name: "Shante Anderson",
    role: "Counselor",
    specialty: "MS, LCAS",
    description: "Trauma, Spiritual Wellness, DWI",
    imageUrl: "/images/employees/shante_anderson.jpeg",
  },
  {
    id: 5,
    name: "Jacquelyn Blake",
    role: "Counselor",
    specialty: "LCSWA, LCASA, CBT",
    description: "Trauma, Addictions, Psychodynamic Therapy and Mindfulness",
    imageUrl: "/images/employees/jacquelyn_blake.png",
  },
  {
    id: 6,
    name: "Tiffany Smith",
    role: "Counselor",
    specialty: "MSW, LCSWA",
    description:
      "Trauma processing using Brainspotting, Written Exposure, Cognitive Processing Therapy",
    imageUrl: "/images/employees/tiffany_smith.png",
  },
  {
    id: 7,
    name: "Joshua Simpson",
    role: "Counselor",
    specialty: "MA, LAPC, LCMHC-A, NCC",
    description:
      "Relationships, Black Men's Issues, Teen Counseling, Women's Issues, Christian Spirituality",
    imageUrl: "/images/employees/joshua_simpson.png",
  },
  {
    id: 8,
    name: "Tamara Thomas, Ph.D",
    role: "Counselor",
    specialty: "LCMHCA, CRC, CBT",
    description: "Trauma, Grief Counselor, Educator and Trainer",
    imageUrl: "/images/employees/tamara_thomas.png",
  },
  {
    id: 9,
    name: "Scott Haskins",
    role: "Counselor",
    specialty: "MSRC, LCAS-A",
    description:
      "Motivational Interviewing, Holistic Practices for those living with Addiction, Relapse Prevention and Maintenance",
    imageUrl: "/images/employees/scott_haskins.png",
  },
  {
    id: 10,
    name: "Karen Coston",
    role: "Counselor",
    specialty: "MSW, CBT, LCSWA Spec",
    description: "Children and Adolescents, Play Therapy",
    imageUrl: "/images/employees/karen_coston.jpeg",
  },
  {
    id: 11,
    name: "Lindsay Locklear",
    role: "Counselor",
    specialty: "MS, LCMHCA, VBT",
    description: "Trauma, Play Therapy, Sand Tray",
    imageUrl: "/images/employees/lindsay_locklear.png",
  },
  {
    id: 12,
    name: "Raziya Health-Booker",
    role: "Counselor",
    specialty: "MSW, LCASA, LCSWA, CBT",
    description:
      "Play Therapy , Solution focused therapy, Addiction Counseling",
    imageUrl: "/images/employees/raziya_health-booker.jpeg",
  },
];
